#!/bin/bash
echo "echo" "Correct :" | bash;
echo "echo" "" | bash;
echo "echo" '' | bash;
echo "echo" "\|" | bash;
echo "echo" '\|' | bash;
echo "echo" "\|\""\" | bash;
echo "echo" '\"\"' | bash;
echo "echo" "\'\'" | bash;
echo "echo" '\"' | bash;
echo "echo" "\'" | bash;
echo "echo" "\|\'" | bash;
echo "echo" '\|\"' | bash;
echo "echo" '\\"\\"' | bash;
echo "echo" "\\'\\" | bash;
echo "echo" "\\'\'" | bash;
echo "echo \\"| bash;
echo "echo \"\""| bash;
echo "echo" "\\\"" | bash;
echo "echo" '\$ \" \' | bash;
echo "echo" '\[ \] \\ \`' | bash;
echo "echo" '\: \; \< \> \= \?' | bash;
echo "echo" "\: \; \< \> \= \?" | bash;
echo "echo" \"\: \; \< \> \= \?\" | bash;
echo "echo" \'\: \; \< \> \= \?\' | bash;
echo "echo" \\'\: \; \< \> \= \?\\' | bash;
echo "echo" " \"a\" " | bash;
echo "echo" " \'a\' " | bash;
echo "echo" " \\'a\\' " | bash;
echo "echo" " \\\'a\\\' " | bash;
echo "echo" a\\ a | bash;
echo "echo" \\\\ | bash;
echo "echo" 'a \\ a' | bash;
echo "echo" "a\"a\"a" | bash;
echo "echo" $ | bash;
echo "echo" \$ | bash;
echo "echo" \\$ | bash;
echo "echo" $USER | bash;
echo "echo" \$USER | bash;
echo "echo" \\$USER | bash;
echo "echo" \\\$USER | bash;
echo "echo" $war | bash;
echo "echo" \$war | bash;
echo "echo" \\$war | bash;
echo "echo" \\\$war | bash;
echo "echo" '$war' | bash;
echo "echo" '\$war' | bash;
echo "echo" '\\$war' | bash;
echo "echo" '\\\$war' | bash;
echo "echo" "$war" | bash;
echo "echo" "\$war" | bash;
echo "echo" "\\$war" | bash;
echo "echo" "\\\$war" | bash;
echo "echo" "$USER" | bash;
echo "echo" "\$USER" | bash;
echo "echo" "\\$USER" | bash;
echo "echo" '$USER' | bash;
echo "echo" '\$USER' | bash;
echo "echo" '\\$USER' | bash;
echo "echo" "\|\\$USER" | bash;
echo "echo" "\|\\\$USER" | bash;
echo "echo" "\\\"$USER" | bash;
echo "echo" '\|\\$USER' | bash;
echo "echo" '\|\\\$USER' | bash;
echo "echo" '\\\"$USER' | bash;
echo "echo" ' \" \' | bash;
echo "echo" "\$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|" | bash;
echo "echo" \"\$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|\" | bash;
echo "echo" '\$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|' | bash;
echo "echo" \'\$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|\' | bash;
echo "echo" \$ \! \@ \# \% \^ \& \* \( \) \_ \+ \| | bash;
echo "echo" \\\$ \\\! \\\@ \\\# \\\% \\\^ \\\& \\\* \\\( \\\) \\\_ \\\+ \\\| | bash;
echo "echo" "\: \; \< \> \= \?" | bash;
echo "echo" "\: \; \< \> \= \?" | bash;
echo "echo" \'\: \; \< \> \= \?\' | bash;
echo "echo" \"\: \; \< \> \= \?\" | bash;
echo "echo" '\[ \] \\ \`' | bash;
echo "echo" \'\[ \] \\ \`\' | bash;
echo "echo" "----------------------------" | bash;
echo "echo" "Incorrect :" | bash;
echo "echo" "'" | bash;
echo "echo" \\\'\: \; \< \> \= \?\\\' | bash;
echo "echo" "\[ \] \\ \`" | bash;
echo "echo" '\\[ \\] \\\ \\`' | bash;
echo "echo" "\$ \" \' " | bash;
echo "echo" \|\"\\ | bash;
echo "echo" '"' | bash;
echo "echo" "\"" | bash;
echo "echo" '\|\"'\' | bash;
echo "echo" '\|\""\' | bash;
echo "echo" "\\'\"" | bash;
echo "echo" ' \' \' | bash;
