run_test 'echo \n\n'
run_test 'echo ""' 
run_test 'echo \|' 
run_test 'echo \"\"' 
run_test 'echo \\'|  
run_test 'echo \\\\' 
run_test 'echo \|\|' 
run_test 'echo \\\|\\\|' 
run_test 'echo \\"\\"' 
run_test 'echo \$ \"' 
run_test 'echo \[ \] \\ \`' 
run_test 'echo \: \ \< \> \= \?\' 
run_test 'echo \"a\"' 
run_test 'echo \\"a\\"' 
run_test 'echo "\\a\\"' 
run_test 'echo \\\"a\"\\' 
run_test 'echo a\\a' 
run_test 'echo a\"\a' 
run_test 'echo $' 
run_test 'echo \$' 
run_test 'echo \\$' 
run_test 'echo $USER' 
run_test 'echo \$USER' 
run_test 'echo \\$USER' 
run_test 'echo \\\$USER' 
run_test 'echo $war' 
run_test 'echo \$war' 
run_test 'echo \\$war' 
run_test 'echo \\\$war' 
run_test 'echo \|\\$USER' 
run_test 'echo \|\\\$USER' 
run_test 'echo \\\"$USER' 
run_test 'echo \|\\$USER' 
run_test 'echo \|\\\$USER' 
run_test 'echo \\\"$USER' 
run_test 'echo \$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|' 
run_test 'echo \$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|' 
run_test 'echo \"\$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|\"' 
run_test 'echo \$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|' 
run_test 'echo \$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|' 
run_test 'echo \\\$ \\\! \\\@ \\\# \\\% \\\^ \\\& \\\* \\\( \\\) \\\_ \\\+ \\\|' 
run_test 'echo \: \ \< \> \= \?\' 
run_test 'echo "\: \ \< \> \= \?\"' 
run_test 'echo \[ \] \\ \`' 
run_test 'echo \[ \] \\ \`\'
