#!/bin/bash
echo 'echo' '\n\n' | ./minishell;
echo 'echo' '' | ./minishell;
echo 'echo' '\|' | ./minishell;
echo 'echo' '\|' | ./minishell;
echo 'echo' '\"\"' | ./minishell;
echo 'echo' '\\'| ./minishell;
echo 'echo' '\\\\' | ./minishell;
echo 'echo' '\|\|' | ./minishell;
echo 'echo' '\\\|\\\|' | ./minishell;
echo 'echo' '\\"\\"' | ./minishell;
echo 'echo' '\$ \"' | ./minishell;
echo 'echo' '\[ \] \\ \`' | ./minishell;
echo 'echo' \'\: \; \< \> \= \?\' | ./minishell;
echo 'echo' '\"a\"' | ./minishell;
echo 'echo' '\\"a\\"' | ./minishell;
echo 'echo' '"\\a\\"' | ./minishell;
echo 'echo' '\\\"a\"\\' | ./minishell;
echo 'echo' 'a\\a' | ./minishell;
echo 'echo' 'a\"\a' | ./minishell;
echo 'echo' '$' | ./minishell;
echo 'echo' '\$' | ./minishell;
echo 'echo' '\\$' | ./minishell;
echo 'echo' '$USER' | ./minishell;
echo 'echo' '\$USER' | ./minishell;
echo 'echo' '\\$USER' | ./minishell;
echo 'echo' '\\\$USER' | ./minishell;
echo 'echo' '$war' | ./minishell;
echo 'echo' '\$war' | ./minishell;
echo 'echo' '\\$war' | ./minishell;
echo 'echo' '\\\$war' | ./minishell;
echo 'echo' '\|\\$USER' | ./minishell;
echo 'echo' '\|\\\$USER' | ./minishell;
echo 'echo' '\\\"$USER' | ./minishell;
echo 'echo' '\|\\$USER' | ./minishell;
echo 'echo' '\|\\\$USER' | ./minishell;
echo 'echo' '\\\"$USER' | ./minishell;
echo 'echo' '\$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|' | ./minishell;
echo 'echo' \'\$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|\' | ./minishell;
echo 'echo' '\"\$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|\"' | ./minishell;
echo 'echo' '\$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|' | ./minishell;
echo 'echo' '\$ \! \@ \# \% \^ \& \* \( \) \_ \+ \|' | ./minishell;
echo 'echo' '\\\$ \\\! \\\@ \\\# \\\% \\\^ \\\& \\\* \\\( \\\) \\\_ \\\+ \\\|' | ./minishell;
echo 'echo' \'\: \; \< \> \= \?\' | ./minishell;
echo 'echo' \"\: \; \< \> \= \?\" | ./minishell;
echo 'echo' '\[ \] \\ \`' | ./minishell;
echo 'echo' \'\[ \] \\ \`\' | ./minishell;
echo 'echo' '----------------------------' | ./minishell;
echo 'echo' 'Incorrect :' | ./minishell;
echo 'echo' '\"\' | ./minishell;
echo 'echo' '\|\""\' | ./minishell;
echo 'echo' '\' | ./minishell;
echo 'echo' '\\\'| ./minishell;
echo 'echo' '\\\"a\\\' | ./minishell;
